
FROM qcdis/miniconda3:v0.1 AS build
COPY download-dev-user-name-at-domain-com-environment.yaml .
RUN conda env update -n venv -f download-dev-user-name-at-domain-com-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM python:3.11-slim-bullseye AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY download-dev-user-name-at-domain-com.py .
