
FROM continuumio/miniconda3:23.10.0-1 AS build
COPY visualize-rasterio-dev-user-name-at-domain-com-environment.yaml .
RUN conda config --remove channels defaults
RUN conda env update -n venv -f visualize-rasterio-dev-user-name-at-domain-com-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM jupyter/base-notebook AS runtime
COPY --from=build /venv /venv
COPY visualize-rasterio-dev-user-name-at-domain-com.py .
COPY visualize-rasterio-dev-user-name-at-domain-com.ipynb .
