
FROM qcdis/miniconda3:v0.1 AS build
COPY a-very-long-cell-name-a-very-long-cell-namea-very-long-cell-namea-very-long-cell-namea-very-long-cell-namea-very-long-cell-gabriel-pelouze-at-lifewatch-eu-environment.yaml .
RUN conda env update -n venv -f a-very-long-cell-name-a-very-long-cell-namea-very-long-cell-namea-very-long-cell-namea-very-long-cell-namea-very-long-cell-gabriel-pelouze-at-lifewatch-eu-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM python:3.11-slim-bullseye AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY a-very-long-cell-name-a-very-long-cell-namea-very-long-cell-namea-very-long-cell-namea-very-long-cell-namea-very-long-cell-gabriel-pelouze-at-lifewatch-eu.py .
