FROM jupyter/r-notebook:70178b8e48d7

USER root

RUN R -e "install.packages('optparse', repos='http://cran.rstudio.com')"

RUN mkdir -p /app
COPY 1-set-file-name-=-phytoplankton--progetto-strategico-2009-2012-australia-csv-spiros-koulouzis-at-lifewatch-eu.R /app
