FROM jupyter/r-notebook:70178b8e48d7

USER root

RUN R -e "install.packages('optparse', repos='http://cran.rstudio.com')"

RUN mkdir -p /app
COPY 2-set-file-name-=-2-fileinformativo-operatore-csv-spiros-koulouzis-at-lifewatch-eu.R /app
